// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	model "github.com/seigaalghi/e-library/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateSchedule provides a mock function with given fields: pickup, dropoff, book
func (_m *Repository) CreateSchedule(pickup time.Time, dropoff time.Time, book *model.Books) (bool, error) {
	ret := _m.Called(pickup, dropoff, book)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, *model.Books) (bool, error)); ok {
		return rf(pickup, dropoff, book)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, *model.Books) bool); ok {
		r0 = rf(pickup, dropoff, book)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time, *model.Books) error); ok {
		r1 = rf(pickup, dropoff, book)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
